name: nlp-reviews
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=2.1.4
  - scikit-learn>=1.0.0
  - nltk>=3.6.0
  - spacy>=3.0.0
  - transformers>=4.36.2
  - pytorch>=1.9.0
  - tensorflow>=2.8.0
  - plotly>=5.18.0
  - streamlit>=1.31.0
  - torch==2.1.0
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - python-dotenv>=0.19.0
  - jupyter>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - wordcloud>=1.8.0
  - ipykernel
  - pip 